---
__db_enable_upgrades:           "{{ db_enable_upgrades | default(false) }}"
__db_version:                   "{{ db_version | default('7.0') }}"
__download_location:            "{{ db2_wizards_download_location | default('c7lb1.cnx.cwp.pnp-hcl.com:8001/Connections7') }}"
__package_name:                 "{{ db2_wizards_package_name | default('HCL_Connections_7.0_wizards_lin_aix.tar') }}"
__db2_extraction_folder:            "{{ db2_extraction_folder | default('/opt/HCL/DB2Wizards') }}"
__installation_folder:          "{{ __db2_extraction_folder }}/Wizards"

__docs_download_location:       "{{ cnx_docs_download_location | default('http://c7lb1.cnx.cwp.pnp-hcl.com:8001/Docs') }}"
__docs_package_name:            "{{ cnx_docs_package_name | default('IBMConnectionsDocs_2.0.1.zip') }}"
__docs_extraction_folder:       "{{ docs_extraction_folder | default('/opt/HCL/InstallBinaries/Docs') }}"
__docs_installation_folder:     "{{ __docs_extraction_folder }}/SetupDB/db2"

__db2_installation_folder:     "{{ db2_installation_folder | default('/opt/IBM/db2/V11.1') }}"
__db2_user:                     "{{ db2_user | default('db2inst1') }}"
__db2_migration_cmd:            "{{ __db2_installation_folder }}/bin/db2 -td@ -vf"
__db2_icec_migration_cmd:       "{{ __db2_installation_folder }}/bin/db2 -tvf"
__db2_home:                     "/home/{{ __db2_user }}"
__db2_instance_homedir:         "{{ db2_instance_homedir | default(__db2_home) }}"

__cnx_force_repopulation:       "{{ cnx_force_repopulation | default(false) }}"
__cnx_docs_force_repopulation:  "{{ cnx_docs_force_repopulation | default(false)|bool }}"

__success_file:                 "{{ __db2_instance_homedir }}/migration.success"
__ic360_success_file:           "{{ __db2_instance_homedir }}/ic360_migration.success"
__sharepoint_success_file:      "{{ __db2_instance_homedir }}/sharepoint_migration.success"
__docs_success_file:            "{{ __db2_instance_homedir }}/docs.migration.success"

__setup_connections_wizards:    "{{ setup_connections_wizards | default(true) }}"
__setup_connections_docs:       "{{ setup_connections_docs | default(false)|bool}}"
