---
- name:                    Setup Operating System
  include_tasks:           setup_os.yml
  when:                    __setup_environment == true and (inventory_hostname in groups["docs_servers"] or inventory_hostname in groups["conversion_servers"] or inventory_hostname in groups["viewer_servers"] or inventory_hostname in groups["proxy_servers"])

- name:                    Create docs user to setup job target
  include_tasks:           create_docs_user.yml
  when:                    __setup_environment == true and (inventory_hostname in groups["docs_servers"] or inventory_hostname in groups["conversion_servers"] or inventory_hostname in groups["viewer_servers"] or inventory_hostname in groups["proxy_servers"] or inventory_hostname in groups["ihs_servers"] or inventory_hostname in groups["dmgr"])

- name:                    Mount Docs NFS shares
  include_tasks:           mount_docs_nfs_shares.yml
  when:                    __setup_environment == true and (inventory_hostname in groups["docs_servers"] or inventory_hostname in groups["conversion_servers"] or inventory_hostname in groups["viewer_servers"])

- name:                    Create Docs DB user if not exists
  include_tasks:           create_db_user.yml
  when:                    inventory_hostname in groups["db2_servers"]
