---
__force_destroy_kubernetes:               "{{ force_destroy_kubernetes | default(false) }}"
__force_destroy_db2:                      "{{ force_destroy_db2 | default(false) }}"
__force_destroy_ihs:                      "{{ force_destroy_ihs | default(false) }}"
__force_destroy_websphere:                "{{ force_destroy_websphere | default(false) }}"
__force_destroy_oracle:                   "{{ force_destroy_oracle | default(false) }}"

__nfsMasterAddress:                       "{{ nfsMasterAddress | default( hostvars[groups['nfs_servers'][0]]['ansible_default_ipv4']['address'] ) }}"
__persistentVolumePath:                   "{{ persistentVolumePath | default('pv-connections') }}"
__nfs_master_files_dest:                  "{{ __nfsMasterAddress }}:/{{ __persistentVolumePath }}"
__nfs_master_files_mount:                 "/mnt/pv-connections"
