---
__force_destroy_kubernetes:               "{{ force_destroy_kubernetes | default(false) }}"
__force_destroy_db2:                      "{{ force_destroy_db2 | default(false) }}"
__force_destroy_ihs:                      "{{ force_destroy_ihs | default(false) }}"
__force_destroy_websphere:                "{{ force_destroy_websphere | default(false) }}"
__force_destroy_oracle:                   "{{ force_destroy_oracle | default(false) }}"
