# Cleanup
---
- name:                    Gather facts
  hosts:                   nfs_servers
  tasks:                   []

- name:                    Cleanup stuff
  hosts:                   k8s_masters, k8s_workers
  become:                  true
  roles:
    - roles/hcl/cleanup

