---
- name:                    Remove the existing Update Wizard on the server at {{ __cnx_install_location }}/updateInstaller
  file:                    path={{ __cnx_install_location }}/updateInstaller state=absent

- name:                    Create a new updateInstaller directory
  file:                    path={{ item }} state=directory mode=0755
  with_items:
    - "{{ __cnx_install_location }}/updateInstaller/fixes"
    - "{{ __tmp_dir }}/cnx-ifix/"

- name:                    Download the updateInstaller
  get_url:
    url:                   "{{ cnx_repository_url }}/{{ __cnx_ifix_installer }}"
    dest:                  "{{ __tmp_dir }}/cnx-ifix/{{ __cnx_ifix_installer }}"
    mode:                  0755

- name:                    Extract the updateInstaller
  unarchive:
    src:                   "{{ __tmp_dir }}/cnx-ifix/{{ __cnx_ifix_installer }}"
    dest:                  "{{ __cnx_install_location }}/updateInstaller"
    copy:                  no
  register:                download_and_unpack_connections_upgradeinstaller
  until:                   download_and_unpack_connections_upgradeinstaller is succeeded
  retries: 3

- name:                    Add +x to updateInstaller
  file:
    dest:                  "{{ __cnx_install_location }}/updateInstaller/HCL_Connections_Install/tools/updateInstaller/updateSilent.sh"
    mode:                  "740"

- name:                    Download the iFixes {{ ifix_file }}
  get_url:
    url:                   "{{ cnx_repository_url }}/{{ ifix_file }}"
    dest:                  "{{ __cnx_install_location }}/updateInstaller/fixes"
    mode:                  0755
