- name:                    Scale Component Pack to the number of workers
  shell:                   kubectl scale --replicas={{ groups['k8s_workers'] | length }} deployment $(kubectl get deployment -n {{ __default_namespace }} | awk {'print $1'} | grep -v NAME) -n {{ __default_namespace }}
  become_user:             "{{ __sudo_user }}"
