- name:                      Find orientme helm file
  find:
    paths:                   "{{ __helmbuilds_folder }}"
    patterns:                "orientme-*.tgz"
    file_type:               file
  register:                  orientme_tgz

- name:                      Found orientme file
  debug:
    msg:                     "{{ orientme_tgz.files[0].path }}"

- name:                      "Render {{ __orientme_env }}"
  template:
    src:                     "helmvars/orientme.yml.j2"
    dest:                    "{{ __orientme_env }}"
  become_user:               "{{ __sudo_user }}"

- name:                      Setup orientme
  command:                   "helm upgrade orientme {{ orientme_tgz.files[0].path }} -i -f {{ __orientme_env }} --namespace {{ __default_namespace }}"
  become_user:               "{{ __sudo_user }}"

- name:                      Give it some space...
  pause:
    seconds:                 300

- name:                      Check if orientme is up and running
  shell:                     kubectl get pods -n {{ __default_namespace }} | grep -i orient | grep -i Running
  when:                      not __skip_pod_checks
  become_user:               "{{ __sudo_user }}"
