---
- name:                    Check Vars
  include_tasks:           check_vars.yml
  when:
    - inventory_hostname in groups["dmgr"]

- name:                    Setup Operating System
  include_tasks:           setup_os.yml

- name:                    Define Vars
  include_tasks:           define_vars.yml
  when:
    - inventory_hostname in groups["dmgr"]

- name:                    Download and Extract MT zip
  include_tasks:           download_extract_mt_zip.yml
  when:
    - inventory_hostname in groups["dmgr"]
    - version_already_installed.stdout|length != 0

- name:                    Install AutoDeploy
  include_tasks:           setup_autodeploy.yml
  when:
    - inventory_hostname in groups["dmgr"]

- name:                    Update Connections MT (Dmgr)
  include_tasks:           setup_mt_dmgr.yml
  when:
    - inventory_hostname in groups["dmgr"]

- name:                    Update Connections MT (if IHS not in Dmgr node)
  include_tasks:           setup_mt_ihs.yml
  when:
    - inventory_hostname in groups["ihs_servers"] and inventory_hostname not in groups["dmgr"]

- name:                    Update Connections MT (if DB not in Dmgr node)
  include_tasks:           setup_mt_db.yml
  when:
    - inventory_hostname in groups["db2_servers"] and inventory_hostname not in groups["dmgr"]


- name:                    Update Connections MT (if WAS not in Dmgr node)
  include_tasks:           setup_mt_was.yml
  when:
    - inventory_hostname in groups["was_servers"] and inventory_hostname not in groups["dmgr"]
