---
- name:               Verify if MT (WAS) is already updated ({{ __mt_update_was_success_file }})
  stat:
    path:             "{{ __mt_update_was_success_file }}"
  register:           mt_was_already_installed

- name:               Synchronize MT Update installation directory to WAS server temp location
  synchronize:
    src:              "{{ __tmp_dir }}/mt/"
    dest:             "/tmp/mt/"
  delegate_to:        "{{ dmgr_hostname }}"
  become:             false
  when:               not mt_was_already_installed.stat.exists

- name:               Copy the files to {{ __tmp_dir }}/mt
  copy:
    src:              "/tmp/mt/"
    dest:             "{{ __tmp_dir }}/mt/"
    remote_src:       yes
  when:               not mt_was_already_installed.stat.exists

- name:               Delete MT Update installation directory from temp location
  file:
    path:             "/tmp/mt/"
    state:            absent
  when:               not mt_was_already_installed.stat.exists

- name:                Run MT Update (WAS)
  shell: |
     set timeout 300
     ./connections-mt-appserver-update-cli.sh config.properties 2>&1 | tee mtupdate_was.log
  args:
      chdir:           "{{ __tmp_dir }}/mt/install"
  become:              true
  when:
      - not mt_was_already_installed.stat.exists
  register:            mt_update_was_performed
  failed_when:         "'Updating HCL Connections MT configuration for Application Server Node' not in mt_update_was_performed.stdout"

- name:                Search for potential errors
  become:              yes
  shell:               "grep -i 'exception' {{ __tmp_dir }}/mt/install/mtupdate_db.log"
  register:            mt_update_was_error_found
  failed_when:         mt_update_was_error_found.stdout|length != 0 and not __mt_skip_error_checking|bool
  when:
    - mt_update_was_performed is not skipped

- name:               Creates HCL directory
  file:
    path:             "{{ __cnx_install_location }}"
    state:            directory    

- name:               "Create {{ __mt_update_was_success_file }} file"
  file:
    path:             "{{ __mt_update_was_success_file }}"
    state:            touch
  when:
    - mt_update_was_performed is not skipped
    - mt_update_was_error_found.stdout|length == 0 or __mt_skip_error_checking|bool
